### ISSUE TITLE
"Select all matching query" not working.

### ISSUE THREAD

**Issue by Nealtron** [Onemind-Services-LLC/netbox-metatype-importer#50]
### NetBox Version

v3.7.6

### NetBox Plugin Version

v0.3.2

### Steps to Reproduce

Open the filter tab, enter a vendor name and hit search. 

Check the "Select All" box, and then check the "Select all XXX meta types matching query" box and click "Delete Selected". 

### Expected Behavior

That it would perform whatever action you desired against only the objects that matched your query. 

### Observed Behavior

It attempts to do perform that action against all devices.

![image](https://github.com/Onemind-Services-LLC/netbox-metatype-importer/assets/6655394/f757e783-b588-44ff-afaf-e2c67c4f29d9)

![image](https://github.com/Onemind-Services-LLC/netbox-metatype-importer/assets/6655394/607f78a9-d7a6-46d8-b2bf-6330cce9a663)

**Comment by Nealtron** [comment]
It also seems to be bugged when you use the simple search box instead of the Filter tab. 

![image](https://github.com/Onemind-Services-LLC/netbox-metatype-importer/assets/6655394/4fc9dfca-8a46-42c8-8e0d-7bb3df0fe9ac)

**Comment by mjoshionemind** [comment]
The issue with filtering without the filter tab in NetBox was resolved in version 4.0.11. I have implemented a fix for the filter tab issue in [this PR](https://github.com/Onemind-Services-LLC/netbox-metatype-importer/pull/54). Now, when filtering through the filter tab, it will display the exact number of instances that match the filter criteria, rather than showing all instances.
